### ISSUE TITLE
User doesn't register after loading app

### ISSUE THREAD

**Issue by shaulhadar** [OneSignalDevelopers/OneSignal-Ionic-Sample#1]
Hello OneSignal, thanks for your great service.
I did all the instructions and uploaded my app, and than tried to send myself a push notification.
but nothing happenes and it says there isn't any users registered.

How am i supposed to register myself to check the app?

THanks,
Shaul.

**Comment by jkasten2** [comment]
Hello,

Can you add the following line to www\js\app.js before OneSignal.init

``` javascript
window.plugins.OneSignal.setLogLevel({logLevel: 4, visualLevel: 4});
```

This will print and show alert boxes on your Android device to help debug the issue. If you're not seeing anything different on your device try adding `alert` and `console.log` before and after each call to OneSignal to make sure the code is running.

You can also check our [Troubleshooting](http://documentation.onesignal.com/docs/common-problems) for a few more things to try.

If you're still seeing issues feel to send us your APK and full logcat to support@onesignal.com or via our help in the bottom right hand corner in our dashboard.

Thanks.

**Comment by firaskudsy** [comment]
am getting the same and after setting the 
window.plugins.OneSignal.setLogLevel({logLevel: 4, visualLevel: 4});

i get a message : 

OneSignal AppId format is invalid

i followed the steps to get the appid exactly from Google developer console. 

any help ?

**Comment by imadarchid** [comment]
@firaskudsy I think you need to get AppId from your OneSignal account, and the Google project number from Google Developer Console if you're planning to build with Android.
