### ISSUE TITLE
error starting

### ISSUE THREAD

**Issue by blondie63** [OneSignalDevelopers/OneSignal-Ionic-Sample#11]
I've tried to use this sample with Ionic pro
But running i've this error:
<img width="1261" alt="onesignal-sample-ionic" src="https://user-images.githubusercontent.com/1261851/33517325-ae4d9dfa-d782-11e7-98de-c7edf32e9c5d.png">

Some help?
Thanks

**Comment by blondie63** [comment]
After some research i seen that on readme.md something is missing:
cocoapods is requested (https://cocoapods.org/)
But the same app start with error
Is it possible that problem is for Ionic 3 ?

**Comment by jkasten2** [comment]
@blondie63 You must run your app on an iOS or Android device. The `onesignal-cordova-plugin` does not run from the the browser.

**Comment by blondie63** [comment]
oh sorry, i've seen now..
at now Ionic Pro support only some plugin for Ionic DevApp testing
http://ionicframework.com/docs/pro/view.html#plugin-support

**Comment by jkasten2** [comment]
@blondie63 Thanks for the link. Since our plugin uses native code for iOS and Android it doesn't work with "Ionic View". They would need to bundle our plugin for it to be supported. You will need to do a full build instead to test your app.
