### ISSUE TITLE
How to turn on screen?

### ISSUE THREAD

**Issue by Matsuo32** [OneSignalDevelopers/OneSignal-Ionic-Sample#12]
I have a problem about turn on screen(wake up) android when message(push notification) incoming, Right now it just sound and vibration in back screen, there is message popup.

**Comment by jkasten2** [comment]
@Matsuo32 This depends on the phone and it's systems settings if this will happen on the device. For example the Samsung Galaxy S8 does this but the user may turn it off as this thread references.
https://us.community.samsung.com/t5/Galaxy-S8-Questions-and-Answers/Any-notification-wakes-up-my-phone-display-on-my-Samsung-S8-Help/td-p/136058

**Comment by Matsuo32** [comment]
@jkasten2  Thank you for suggest me. I already tried all as below but it still have same problem.
Could you have another way for fixed this.

>     Settings > Lock Screen & Security > Notifications > Disable (slider)
>     Settings > Display > Keep screen turned off (This will prevent the screen from turning on while the device is in a dark place like your pocket or bag)
>     Settings > Notifications > Advanced > Always On Display > Do not show content on lock screen (also do not set as a priority)
>     You can also adjust other apps in your notification settings and make sure they do not show on the lock screen. When they are set to do that, they may wake up the screen.

**Comment by jkasten2** [comment]
@Matsuo32 What exact devices are you testing on? It is up to the device if the screen should turn on if a notification is received. It isn't something the app has control over

**Comment by Matsuo32** [comment]
@jkasten2  my device is Samsung J7 android version 7. I already tried with different Samsung it same problem. then i tried to add  <uses-permission android:name="android.permission.WAKE_LOCK" /> in AndroidManifest.xml for wake up but it still problem.
