### ISSUE TITLE
One signal haven't detected any subscribed users yet for this platform.

### ISSUE THREAD

**Issue by hamdanihamza** [OneSignalDevelopers/OneSignal-Ionic-Sample#13]
On android, I added One Signal plugin on my app and i added this code on the platform.ready section

```
    window["plugins"].OneSignal.setLogLevel({logLevel: 6, visualLevel: 6});
      var notificationOpenedCallback = function(jsonData) {
        console.log('notificationOpenedCallback: ' + JSON.stringify(jsonData));
      };

      window["plugins"].OneSignal
        .startInit("******-****-****-****-***********", "**********")
        .handleNotificationOpened(notificationOpenedCallback)
        .endInit();
```

as i launch the app it shows a bunch of alerts sending requests to onesignal and the app suddenly closes and onesignal doesn’t detect any subscribers.

**Comment by jkasten2** [comment]
@hamdanihamza Are you seeing this issue on Android or iOS? Can you provide the crash log so we can look into this?

**Android - Logcat log:**
https://documentation.onesignal.com/docs/troubleshooting-android#section-how-to-get-a-crash-or-error-log-from-an-android-device

**iOS - Xcode crash log:**
https://documentation.onesignal.com/docs/troubleshooting-ios#section-how-to-get-a-crash-log-from-an-ios-device

I please list all your plugins in your project to help debug the issue.
`ionic cordova plugin list`

**Comment by jayinai** [comment]
@jkasten2 I think s/he is on Android. I am on iOS and face the same issue. Here is the result after running `ionic cordova plugin list` as you suggested:

```
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.4.1 "OneSignal Push Notifications"
```

**Comment by Nightsd01** [comment]
@ShuaiW I don’t think any of those plugins would cause an incompatibility issue, however there are a few things that could cause this issue. 

I would suggest making sure your app is actually requesting the user’s permission to allow push notification. If it is, you should also enable verbose logging by calling `OneSignal.setLogLevel(6, 0)` and make sure you are seeing the `playerId` (the OneSignal user ID) get set. 

You’ll also want to make sure you don’t have a mismatched Bundle ID error. In your Xcode project settings you should see a bundle ID (like `com.onesignal.example`) and make sure it matches what you see in OneSignal iOS platform settings.

**Comment by juanfran1512** [comment]
@Nightsd01 i have the same problem that @ShuaiW but i'm in android, could you explain how to do "requesting the user’s permission to allow push notification. " i follow sou much tutorials and i'm starting to get desperated, i spend more then a week traying to do this onesignal push notification,
sorry for my english i'm from venezuela.

**Comment by jkasten2** [comment]
@juanfran1512 On Android there isn't a notification prompt, users are opted in automatically. I recommend checking the All Users page on the OneSignal dashboard to see if your device was subscribed. If there was a subscription issue it will show here.

If not is recommend following the logcat instructions above and ask OneSignal support if you need help looking into the log.
