### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by matthieu-D** [OneSignalDevelopers/OneSignal-Ionic-Sample#2]
First time install
 cordova plugin add onesignal-cordova-plugin
Fetching plugin "onesignal-cordova-plugin" via plugin registry
npm http GET http://registry.cordova.io/onesignal-cordova-plugin
npm http 404 http://registry.cordova.io/onesignal-cordova-plugin
Error: 404 Not Found: onesignal-cordova-plugin
    at RegClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:268:14)
    at Request.self.callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:876:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:827:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11) 

Second time install
cordova plugin add onesignal-cordova-plugin
Fetching plugin "onesignal-cordova-plugin" via npm
Installing "onesignal-cordova-plugin" for android
Error during processing of action! Attempting to revert...
Failed to install 'onesignal-cordova-plugin':Error: Uh oh!
ENOENT, no such file or directory '/Users/matthieu/mobile_projects/OneSignal-Ionic-Example/platforms/android/local.properties'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.createEditor (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/properties-parser/index.js:328:39)
    at getProjectSdkDir (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:36:45)
    at module.exports.framework.install (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:138:35)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:654:27
    at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PlatformApiPoly.addPlugin (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:259:20)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:603:6)
Error: Uh oh!
ENOENT, no such file or directory '/Users/matthieu/mobile_projects/OneSignal-Ionic-Example/platforms/android/local.properties'

cordova plugin list:
onesignal-cordova-plugin 1.9.4 "OneSignal Push Notifications"

In app:
Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:19 Uncaught TypeError: Cannot read property 'OneSignal' of undefined

Your library doesn't work in ionic lab which is what most ionic devs use, only on real device, kinda sucks.
Your check progression on your website only focus on eclipse and visual studio, talking about gradle (something that I have never seen):
<img width="1105" alt="screen shot 2015-12-12 at 17 45 15" src="https://cloud.githubusercontent.com/assets/5333018/11763604/a98eb94c-a0f8-11e5-866e-80f54cd7bf8f.png">
As an ionic developer, this looks more 4-5 hours of incoming trouble.
I installed google play service through android, still not good.
If you want developers to use your product, start working on your documentation otherwise nobody is going to use your product ...

**Comment by jkasten2** [comment]
Hello Matthieu,

Thanks for your feedback, unfortunately Ionic Lab does not have a UI to add 3rd party plugin. I have added a note for Ionic Lab that it has to be added from the terminal to our documentation.

Our plugin requires the Google Play services library and the Android Support Library v4 for Android, this is noted in step [3. Android](https://documentation.onesignal.com/docs/phonegap-sdk-installation#3-android-click-to-expand).

Push notifications requires is a native feature so your must be run on the device for our plugin to work. We will look into seeing if it is possible keep javascript errors from throwing when your app is run from ionic serve.

Our main documentation page will be updated in a few hours but you can see our latest documentation [here](https://documentation.onesignal.com/docs/phonegap-sdk-installation#3-android-click-to-expand?version=1.0.4). Let us know if you have any feedback on it.

Thanks.

**Comment by matthieu-D** [comment]
Ios platform working perfectly (which is what I am using) + magic tools to generate cer,p2,pem. Great work since there are a lot of bugs with Ionic Push. 
Didn't have time to push further at the moment.

**Comment by jkasten2** [comment]
Good to hear iOS is working well for you, we have have released a 1.10.1 version of our Cordova SDK with a number of improvements for Android. You will need to be using Cordova Android platform 4.0.0 or later to use this updated plugin. You can run the following to check and update your project's version of Android.

```
cordova platform
cordova platform update android
```

Thanks.

**Comment by matthieu-D** [comment]
After more search for android.
At the beginning I thought I had 2 android-sdk installed and there was interferences but my PATH and ANDROID_HOME were good so I digged more.

https://forum.ionicframework.com/t/help-me-i-build-android-error-use-plugin-analytics/30439/2
I installed ALL the plugins from extras, not just the mininum.
I copy paste the google-play-service.jar from sdk-android to platform/android/libs.
I then add that to the AndroidManifest.xml
<meta-data android:name="com.google.android.gms.version"
    android:value="@integer/google_play_services_version" />
integer/google_play_services_version wasn't recognised so I put 29.0.0 (the google-play-service-version)
Got this error for value 'Requires 8487000 but found 0', so I replaced 29.0.0 by this value.
And finally it works.
Android's workflow is really bad ...

**Comment by jkasten2** [comment]
Cordova version 5 and greater supports the new Android gradle build system which handles library dependencies for you like Google Play services and the Android Support library. Unfortunately there are a lot of old plugins that still use .jar directly and/or the old ANT build system which creates issues if they try to include a copy of the same libraries.

Our plugin `onesignal-cordova-plugin` is updated to use the gradle build system and depends on both Google Play services and the Android Support library. This main branch of our plugin plays nicely with all other Cordova plugins that also use the gradle.

We provide a compat branch of our plugin `onesignal-cordova-plugin-pgb-compat` that is designed to work nicely with old plugins and old versions of Cordova. This however requires more setup as you have to figure out which other plugins in you app also depend on Google Play services and the Android support library. However we have created a guide on our page of some commonly used plugins and how to get them working together with OneSignal.
https://documentation.onesignal.com/docs/cordova-common-problems

Thanks.
