### ISSUE TITLE
Ionic 2: OneSignalPush.java:251: error: unreported exception JSONException; must be caught or declared to be thrown

### ISSUE THREAD

**Issue by saiy2k** [OneSignalDevelopers/OneSignal-Ionic-Sample#3]
I am trying to integrate OneSignal with my Ionic 2 App.

I installed the plugin, copied the code to app.ts, replaced the App ID and Google Project Number.

Now, when I try to run with `ionic run android`, I am getting this error:

> [ProjectRoot]/platforms/android/src/com/plugin/gcm/OneSignalPush.java:251: error: unreported exception JSONException; must be caught or declared to be thrown
>       OneSignal.setEmail(data.getString(0));
>                                        ^
> 1 error
>  FAILED
> 
> FAILURE: Build failed with an exception.
> - What went wrong:
>   Execution failed for task ':compileDebugJavaWithJavac'.
>   > Compilation failed; see the compiler error output for details.

Android Support Repository v25 and Google Repository v25 are installed.

Please help.

**Comment by jkasten2** [comment]
Hello,

Thanks for the report, just fixed the issue in 1.12.3 of our SDK.

Thanks.

**Comment by ukenpachi** [comment]
I'm getting this error also how do i fix it?

**Comment by jkasten2** [comment]
@ukenpachi Can you run the following to make sure you have the newest version of the OneSignal plugin?

```
cordova plugin list
```
