### ISSUE TITLE
window.plugins.OneSignal doesn't have init function, but has startInit.

### ISSUE THREAD

**Issue by artmaro** [OneSignalDevelopers/OneSignal-Ionic-Sample#5]
It seems that we should use
`window.plugins.OneSignal.startInit('appid','google api id').endInit();` instead of `init`.
Inconsistent information between https://documentation.onesignal.com/docs/ionic-sdk  and https://documentation.onesignal.com/docs/ionic-sdk-setup

**Comment by jkasten2** [comment]
@artmaro Thanks for the report, our documentation and this example have been updated to our new 2.0 SDK.
