### ISSUE TITLE
Info Messages

### ISSUE THREAD

**Issue by TomCosta** [OneSignalDevelopers/OneSignal-Ionic-Sample#7]
Hello! First of all thanks for this awesome plugin!
Second, my question is:
Why this still send INFO messages, all the times at the starting and ending app opening/launching?!
How can I stop this messages?
Thanks in advance!

**Comment by jkasten2** [comment]
@TomCosta Can you include some of the log messages you are seeing?

**Comment by TomCosta** [comment]
Yes, for sure.
It's like this:

![screenshot_20170301-185125](https://cloud.githubusercontent.com/assets/9824969/23483114/554610f8-feb0-11e6-9898-502f4eb74bac.png)

**Comment by jkasten2** [comment]
@TomCosta Please check for `setLogLevel` in your code and remove it.

**Comment by TomCosta** [comment]
OMG!
Thanks a lot!!
